docs/domain_model_v2/definitions/categoryInstance_definition.json
docs/domain_model_v2/definitions/category_definition.json
docs/domain_model_v2/definitions/framework_definition.json
docs/domain_model_v2/definitions/term_definition.json
platform-core/graph-engine/module/graph-engine/src/test/resources/definitions/framework_definition.json
platform-core/unit-tests/src/test/resources/application.conf
platform-jobs/samza/distribution/pom.xml
platform-jobs/samza/image-tagging/pom.xml
platform-jobs/samza/image-tagging/src/main/config/image-tagging.properties
platform-jobs/samza/publish-pipeline/pom.xml
platform-jobs/samza/publish-pipeline/src/main/config/publish-pipeline.properties
platform-modules/actors/src/main/java/org/ekstep/learning/framework/FrameworkHierarchy.java
platform-modules/common/src/main/java/org/ekstep/common/util/HttpRestUtil.java
platform-modules/common/src/main/java/org/ekstep/common/util/S3PropertyReader.java
platform-modules/content-manager/src/main/java/org/ekstep/content/operation/finalizer/BaseFinalizer.java
platform-modules/content-manager/src/main/java/org/ekstep/content/pipeline/BasePipeline.java
platform-modules/ekstep-framework/src/main/java/org/ekstep/framework/mgr/impl/BaseFrameworkManager.java
platform-modules/ekstep-framework/src/main/java/org/ekstep/framework/mgr/impl/FrameworkManagerImpl.java
platform-modules/ekstep-framework/src/test/java/org/ekstep/framework/controller/test/FrameworkV3ControllerTest.java
platform-modules/manager/src/main/java/org/ekstep/taxonomy/mgr/impl/ContentManagerImpl.java
platform-modules/manager/src/test/resources/definitions/framework_definition.json
platform-modules/service/src/main/resources/application.conf
platform-tests/functional-tests/src/test/java/org/ekstep/framework/FrameworkAPITest.java

Framework Changes to Support Translations and Populate Metadata to ElasticSearch

Framework Changes to Support Translations and Populate Metadata to ElasticSearch

---

platform-core/platform-telemetry/src/main/java/org/ekstep/telemetry/TelemetryGenerator.java
platform-core/platform-telemetry/src/main/java/org/ekstep/telemetry/logger/TelemetryManager.java
platform-core/unit-tests/src/test/resources/application.conf
platform-modules/ekstep-dialcode/src/main/java/org/ekstep/dialcode/mgr/impl/DialCodeManagerImpl.java
platform-modules/service/src/main/resources/application.conf
searchIndex-platform/module/search-api/search-manager/app/controllers/SearchBaseController.java
searchIndex-platform/module/search-api/search-manager/app/controllers/SearchController.java
searchIndex-platform/module/search-api/search-manager/app/managers/BasePlaySearchManager.java
searchIndex-platform/module/search-api/search-manager/conf/application.conf

Following Changes are done:
1. Removed Execution Context Dependency from Search Service for "SEARCH" Telemetry Event.
2. Introduced "cdata" and App-Id as part of "cdata".

Search Telemetry - Include App Id in CDATA

---

platform-jobs/samza/distribution/pom.xml
platform-jobs/samza/image-tagging/pom.xml
platform-jobs/samza/publish-pipeline/pom.xml
platform-modules/common/src/main/java/org/ekstep/common/router/RequestRouterPool.java

Reverts project-sunbird/sunbird-learning-platform#76

Revert "Merge Release 1.13.2.1 to Master"

---

platform-jobs/samza/publish-pipeline/src/main/java/org/ekstep/jobs/samza/task/PublishPipelineTask.java

…Adding log for checking time duration for publish

Log added to check publish time

---

platform-jobs/samza/distribution/pom.xml
platform-jobs/samza/publish-pipeline/pom.xml

Content size limits

---

searchIndex-platform/module/search-actors/src/main/java/org/ekstep/search/actor/SearchManager.java
searchIndex-platform/module/search-api/search-manager/conf/application.conf
searchIndex-platform/module/searchindex-common/src/main/java/org/ekstep/searchindex/util/ObjectDefinitionCache.java

Search Service Sending null objectType to GET definition

---

ansible/redis-backup.yml
ansible/roles/redis-backup/defaults/main.yml
ansible/roles/redis-backup/tasks/main.yml
pipelines/backup/redis-backup/Jenkinsfile

@rjshrjndrn Please review and merge

ansible role for Redis backup

---

platform-modules/manager/src/main/java/org/ekstep/content/mgr/impl/operation/plugin/CopyOperation.java
platform-modules/manager/src/main/java/org/ekstep/taxonomy/mgr/impl/BaseContentManager.java
platform-modules/manager/src/test/java/org/ekstep/taxonomy/controller/ContentV3ControllerCopyContentTest.java
platform-modules/manager/src/test/java/org/ekstep/taxonomy/controller/ContentV3ControllerTest.java
platform-modules/manager/src/test/java/org/ekstep/taxonomy/controller/ContentV3PublishLocalTest.java

createdOn was not generated for copied contents

Issue #SB-11602 fix: Copy content metadata issue fix

---

platform-jobs/samza/distribution/pom.xml
platform-jobs/samza/publish-pipeline/pom.xml
platform-jobs/samza/publish-pipeline/src/main/java/org/ekstep/jobs/samza/service/PublishPipelineService.java
platform-modules/actors/src/main/java/org/ekstep/learning/util/ControllerUtil.java
platform-modules/content-manager/src/main/java/org/ekstep/content/operation/finalizer/PublishFinalizer.java
platform-modules/content-manager/src/main/java/org/ekstep/content/publish/PublishTask.java

Content enriched metadata was not getting synced

---

pipelines/deploy/search/Jenkinsfile

Issue #0000: DO-659 added the vault-password-file

---

pipelines/backup/cassandra-backup/Jenkinsfile
pipelines/backup/cassandra-restore/Jenkinsfile
pipelines/backup/elasticsearch-restore/Jenkinsfile
pipelines/backup/elasticsearch/Jenkinsfile
pipelines/backup/neo4j-restore/Jenkinsfile
pipelines/backup/neo4j/Jenkinsfile
pipelines/backup/redis-backup/Jenkinsfile
pipelines/deploy/search/Jenkinsfile

added the vault-passwd-file in all the backup and restore jenkinsfile

added the vault-passwd-file in all the backup and restore jenkinsfile

---

platform-modules/actors/src/main/java/org/ekstep/learning/framework/FrameworkHierarchy.java
platform-modules/ekstep-framework/src/main/java/org/ekstep/framework/mgr/impl/FrameworkManagerImpl.java

Enhancement - Framework objectType enabled cache.
Below if the flow:
- - Save to redis after publish 
- - Read frameworks from Redis
- - If not available, read from cassandra and update Redis

Cache implementation: Framework

---

platform-modules/content-manager/src/main/java/org/ekstep/content/operation/finalizer/PublishFinalizer.java
platform-modules/content-manager/src/main/java/org/ekstep/content/validator/ContentValidator.java
platform-modules/manager/src/main/java/org/ekstep/content/mgr/impl/operation/hierarchy/GetHierarchyOperation.java

Invalid File when sent for review
Retired collection get Hierarchy issue

Release-1.15 prod fixes

---

platform-tools/spikes/size-migration/src/main/java/org/sunbird/lp/content/App.java
platform-tools/spikes/size-migration/src/main/java/org/sunbird/lp/content/Neo4jDBClient.java

Printing failed content
Removing/skiping the failed content to migrate from previous batch.

Issue #SB-11697 Printing failed content

---

ansible/neo4j-es-sync-deploy.yml
ansible/roles/neo4j-es-sync-tool/defaults/main.yml
ansible/roles/neo4j-es-sync-tool/tasks/main.yml
ansible/roles/neo4j-es-sync-tool/templates/application.conf.j2
pipelines/deploy/neo4j-es-sync-composite/Jenkinsfile

Added Ansible roles and jenkins file to download failed events from storage account and sync to neo4j to elasticsearch

neo4j-es compostite sync tool

---

ansible/roles/learning-service/templates/application.conf.j2
ansible/roles/lp-synctool-deploy/defaults/main.yml
ansible/roles/lp-synctool-deploy/templates/application.conf.j2
pipelines/build/learning/Jenkinsfile
pipelines/build/lp-functional-test/Jenkinsfile
platform-core/graph-engine/module/cache-manager/src/main/java/org/ekstep/graph/cache/util/RedisStoreUtil.java
platform-core/unit-tests/src/test/resources/application.conf
platform-jobs/samza/distribution/pom.xml
platform-jobs/samza/publish-pipeline/pom.xml
platform-modules/actors/src/main/java/org/ekstep/learning/framework/FrameworkHierarchy.java
platform-modules/actors/src/main/java/org/ekstep/learning/router/LearningRequestRouter.java
platform-modules/content-manager/src/main/java/org/ekstep/content/operation/finalizer/PublishFinalizer.java
platform-modules/content-manager/src/main/java/org/ekstep/content/util/ContentBundle.java
platform-modules/ekstep-framework/src/main/java/org/ekstep/framework/mgr/impl/BaseFrameworkManager.java
platform-modules/ekstep-framework/src/main/java/org/ekstep/framework/mgr/impl/FrameworkManagerImpl.java
platform-modules/manager/src/main/java/org/ekstep/content/mgr/impl/operation/content/FindOperation.java
platform-modules/manager/src/main/java/org/ekstep/content/mgr/impl/operation/content/RetireOperation.java
platform-modules/manager/src/main/java/org/ekstep/taxonomy/mgr/impl/BaseContentManager.java
platform-modules/service/src/main/resources/application.conf
platform-tools/spikes/content-tool/src/main/java/org/ekstep/content/tool/CloudStoreManager.java
platform-tools/spikes/content-tool/src/main/java/org/ekstep/content/tool/service/BaseService.java
platform-tools/spikes/content-tool/src/main/java/org/ekstep/content/tool/service/SyncService.java
platform-tools/spikes/sync-tool/src/main/java/org/ekstep/sync/tool/mgr/CassandraESSyncManager.java
platform-tools/spikes/sync-tool/src/main/java/org/ekstep/sync/tool/shell/SyncShellCommands.java
pom.xml

Hotfix deployment for publish pipeline changes.

Release 2.0.4

---

ansible/neo4j-es-sync-deploy.yml
ansible/roles/neo4j-es-sync-tool/defaults/main.yml
ansible/roles/neo4j-es-sync-tool/tasks/main.yml
ansible/roles/neo4j-es-sync-tool/templates/application.conf.j2
pipelines/deploy/neo4j-es-sync-composite/Jenkinsfile

neo4j-composite-sync-tool

---

ansible/cassandra-restore.yml
ansible/roles/cassandra-restore/defaults/main.yml
ansible/roles/cassandra-restore/files/cassandra-restore.py
ansible/roles/cassandra-restore/tasks/main.yml
pipelines/restore/cassandra/Jenkinsfile

This addition is required to automate the cassandra restore 
process. Updated the Ansible scripts and added the Jenkinsfile.

Adding the cassandra restore scripts

---

ansible/roles/learning-service/tasks/main.yml
ansible/roles/logstash-deploy/tasks/main.yml
ansible/roles/neo4j-deploy/tasks/main.yml
ansible/roles/search-service-deploy/defaults/main.yml
ansible/roles/search-service-deploy/tasks/main.yml

Added the monit stop, monit start and remove old artifacts tasks in learning, search, neo4j and logstash deployment scripts.

updated the start monit and stop monit tasks in deployment script

---

ansible/cassandra-trigger-deploy.yml
pipelines/build/cassandra-trigger/Jenkinsfile
pipelines/deploy/cassandra/Jenkinsfile.triggers

Added the cassandra trigger build and deployment jenkinsfile and deployment scripts.

Added the cassandra trigger build and deployment automation scripts

---

pipelines/build/learning/Jenkinsfile

This addition is required to take the profileid as user parameter and based on that run the build command and copy the artifacts.

DO-DO-1206 updated the learning jenkinsfile

---

pipelines/build/learning/Jenkinsfile

This reverts commit c6d4d474a2cdffa35aa265b548581c72f2cfca3f.

Revert "Enable unit tests to generate coverage report"

---

ansible/roles/es6/files/templates/experimentindex.json

@maheshkumargangula Please review

Issue #SC-1098 - Changed the doc type for experiment

---

ansible/es_composite_search_cluster_setup.yml

Removed the es_heap_size var from playbook as this var was present in palybook. Hence removed the variable from playbook.

DO-1631 removed the es_heap_size var from playbook

---

platform-modules/manager/src/main/java/org/ekstep/content/mgr/impl/operation/content/FindOperation.java

Issue #SC-0000 fix: Added Cache TTL for Content Read Api

---

platform-jobs/samza/course-batch-updater/src/main/java/org/sunbird/jobs/samza/service/util/BatchStatusUpdater.java

fix for
[ERROR] /var/lib/jenkins/workspace/Build/KnowledgePlatform/Yarn/platform-jobs/samza/course-batch-updater/src/main/java/org/sunbird/jobs/samza/service/util/BatchStatusUpdater.java:[57,48] error: unreported exception ParseException; must be caught or declared to be thrown

fix for parse exception

---

ansible/inventory/env/group_vars/all.yml

Reverts project-sunbird/sunbird-learning-platform#790

Revert "replaced swarm manager lb ip with private ingress ip"

---

ansible/roles/azure-cli/tasks/main.yml

"Failed to update apt cache" installing azure cli

---

ansible/roles/setup-kafka/defaults/main.yml

This topic is being created from the data pipeline Jenkins's job. Hence removing the topics from here.

Issue #0000: Remved the telemetry.ingest topic

---

docs/domain_model_v2/definitions/content_definition.json
docs/domain_model_v2/definitions/content_image_definition.json
platform-jobs/samza/asset-enrichment/pom.xml
platform-jobs/samza/asset-enrichment/src/main/config/asset-enrichment.properties
platform-jobs/samza/asset-enrichment/src/main/config/local.asset-enrichment.properties
platform-jobs/samza/asset-enrichment/src/main/java/org/ekstep/jobs/samza/service/AssetEnrichmentService.java
platform-jobs/samza/asset-enrichment/src/main/java/org/ekstep/jobs/samza/util/OptimizerUtil.java
platform-jobs/samza/distribution/pom.xml
platform-jobs/samza/publish-pipeline/pom.xml
platform-jobs/samza/publish-pipeline/src/main/config/local.publish-pipeline.properties
platform-jobs/samza/publish-pipeline/src/main/config/publish-pipeline.properties
platform-modules/actors/src/main/java/org/ekstep/learning/util/CloudStore.java
platform-modules/content-manager/src/main/java/org/ekstep/content/operation/finalizer/PublishFinalizer.java
platform-modules/content-manager/src/main/java/org/ekstep/content/util/ContentPackageExtractionUtil.java
platform-modules/content-manager/src/main/java/org/ekstep/content/util/PublishFinalizeUtil.java
platform-modules/content-manager/src/test/java/org/ekstep/content/operation/finalizer/PublishFinalizerTest.java
platform-modules/content-manager/src/test/java/org/ekstep/content/util/PublishFinalizeUtilTest.java
platform-modules/content-manager/src/test/resources/definitions/content_definition.json
platform-modules/content-manager/src/test/resources/definitions/content_image_definition.json

SC-1710: Context driven content upload to support program - publish pipeline changes

---

ansible/roles/cassandra-db-update/templates/data.cql.j2
platform-modules/manager/src/main/java/org/ekstep/content/mgr/impl/operation/dialcodes/LinkDialCodeOperation.java

Dialcode link changes for fetching collection from cassandra

---

platform-jobs/samza/auto-creator/pom.xml
platform-jobs/samza/auto-creator/src/main/java/org/ekstep/jobs/samza/service/AutoCreatorService.java
platform-jobs/samza/auto-creator/src/main/java/org/ekstep/jobs/samza/util/ContentUtil.java
platform-jobs/samza/distribution/pom.xml

This PR has below changes:
1. support for h5p upload
2. skip mimeType validation
3. send actual exception to failed topic

Issue #DP-875 feat: auto-creator job enhancement

---

platform-jobs/samza/auto-creator/pom.xml
platform-jobs/samza/auto-creator/src/main/java/org/ekstep/jobs/samza/util/AutoCreatorParams.java
platform-jobs/samza/auto-creator/src/main/java/org/ekstep/jobs/samza/util/ContentUtil.java
platform-jobs/samza/distribution/pom.xml

SC-1889: added textbook linking code for backward compatibility

---

platform-jobs/samza/auto-creator/pom.xml
platform-jobs/samza/auto-creator/src/main/config/auto-creator.properties
platform-jobs/samza/auto-creator/src/main/java/org/ekstep/jobs/samza/service/AutoCreatorService.java
platform-jobs/samza/auto-creator/src/main/java/org/ekstep/jobs/samza/util/AutoCreatorParams.java
platform-jobs/samza/auto-creator/src/main/java/org/ekstep/jobs/samza/util/ContentUtil.java
platform-jobs/samza/distribution/pom.xml

1. added enhancement to support content stage
2. added delay between api calls

SC-1847 feat: added enhancement to support content stage

---

platform-jobs/samza/course-certificate-generator/pom.xml
platform-jobs/samza/course-certificate-generator/src/main/config/course-certificate-generator.properties
platform-jobs/samza/course-certificate-generator/src/main/java/org/sunbird/jobs/samza/service/CertificateGeneratorService.java
platform-jobs/samza/course-certificate-generator/src/main/java/org/sunbird/jobs/samza/service/util/CertificateGenerator.java
platform-jobs/samza/course-certificate-generator/src/main/java/org/sunbird/jobs/samza/util/CourseCertificateParams.java
platform-jobs/samza/course-certificate-generator/src/test/java/org/sunbird/jobs/samza/service/CertificateGeneratorTest.java
platform-jobs/samza/distribution/pom.xml

SB-19999: Reverting - svgTemplate added for certificate scalability

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml

This reverts commit f4796d24e252351377edad657d88d2bf364abcf2.

Flink - Use dp-redis for cache

---

docs/domain_model_v2/definitions/collection_definition.json
docs/domain_model_v2/definitions/collection_image_definition.json
docs/domain_model_v2/definitions/content_definition.json
docs/domain_model_v2/definitions/content_image_definition.json

DIK-4086: Not able to save content on DIKSHA- Adding relatedBoards

---

docs/domain_model_v2/definitions/collection_definition.json
docs/domain_model_v2/definitions/collection_image_definition.json
docs/domain_model_v2/definitions/content_definition.json
docs/domain_model_v2/definitions/content_image_definition.json

DIK-4086: Not able to save content on DIKSHA

---

platform-jobs/samza/distribution/pom.xml
platform-jobs/samza/publish-pipeline/pom.xml
platform-modules/content-manager/src/main/java/org/ekstep/content/util/PublishFinalizeUtil.java

SC-1844: Tag objects with multiple frameworks 

---

platform-jobs/samza/course-certificate-generator-v2/pom.xml
platform-jobs/samza/course-certificate-generator-v2/src/main/java/org/sunbird/jobs/samza/service/util/CertificateGenerator.java
platform-jobs/samza/course-certificate-generator-v2/src/main/java/org/sunbird/jobs/samza/service/util/IssueCertificate.java
platform-jobs/samza/course-certificate-generator-v2/src/main/java/org/sunbird/jobs/samza/util/CourseCertificateParams.java
platform-jobs/samza/course-common/src/main/java/org/sunbird/jobs/samza/util/SunbirdCassandraUtil.java
platform-jobs/samza/distribution/pom.xml
platform-jobs/samza/pom.xml
platform-modules/manager/src/main/java/org/ekstep/taxonomy/controller/ContentV3Controller.java

Certificate Status (certstatus):
- 2 - Certificate issued.
- 3 - Certificate Template criteria didn't match.
Also, disabled the certificate-generator v1 Samza job (PDF certificates).

Certificate Status - Set on 'Criteria validation' and 'Publishing Certificate'

---

platform-jobs/samza/distribution/pom.xml
platform-jobs/samza/publish-pipeline/pom.xml
platform-modules/content-manager/src/main/java/org/ekstep/content/util/PublishFinalizeUtil.java
platform-modules/content-manager/src/test/java/org/ekstep/content/util/PublishFinalizeUtilTest.java

…ld content with old framework category value

SC-1844: Tag objects with multiple frameworks- handling old content with old framework category value

---

platform-jobs/samza/distribution/pom.xml
platform-jobs/samza/pom.xml
platform-jobs/samza/publish-pipeline/pom.xml
platform-jobs/samza/publish-pipeline/src/main/java/org/ekstep/jobs/samza/service/PublishPipelineService.java
platform-jobs/samza/qrcode-image-generator/pom.xml
platform-jobs/samza/qrcode-image-generator/src/main/java/org/ekstep/jobs/samza/service/QRCodeImageGeneratorService.java

SC-2084 : Post Publish - migration to flink

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml

@SMYALTAMASH : Please review it

Issue #000 | Default values added for media config

---

docs/cypher-scripts/release-3.8.0
docs/cypher-scripts/release-3.8.0-all-objects.cypher
docs/cypher-scripts/release-3.8.0.cypher

Adding cypher scripts to execute updating org and target framework specific data for backward compatibility.
Please choose appropriate options.
Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Software versions:
* Hardware versions:

Issue #SB-21954 feat: Adding cypher script for backward compatibility

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

@maheshkumargangula : Kindly review it

SC-2078 : Config Map for Audit history indexer

---

docs/domain_model_v2/definitions/collection_definition.json
docs/domain_model_v2/definitions/collection_image_definition.json
docs/domain_model_v2/definitions/content_definition.json
docs/domain_model_v2/definitions/content_image_definition.json

SB-24023: Adding discussionForum in content and collection schema

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml

SC-1914 - KP flink job package name changes 

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml

Reverts project-sunbird/sunbird-learning-platform#1448

Revert " Flink logging to enable DEBUG"

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

@maheshkumargangula : Please review it

SC-1914 | Content API and timer duration changes added

---

ansible/roles/neo4j-cluster/tasks/main.yml
ansible/roles/redis/defaults/main.yml

This PR includes the changes for redis version upgrade.

corrected the redis home

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

Issue #SB-25131: ECML publish code

---

ansible/inventory/env/group_vars/all.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

This reverts commit 1bae55cbaa5f9682b95a2ea7d37d48d99480f19d.

Revert : Issue #SB-26274 feat: UserFeed API changes

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

Moved the hardcoded list of **restrict.objectTypes** to a variable

Added conf for restrict.objectTypes.

---

platform-jobs/samza/distribution/pom.xml
platform-jobs/samza/publish-pipeline/pom.xml
platform-modules/content-manager/src/main/java/org/sunbird/content/operation/finalizer/PublishFinalizer.java

Issue #SB-27644 fix: Leaf Node Ids fix

Issue #SB-27644 fix: Leaf Node Ids fix

---

ansible/roles/learning-service/templates/application.conf.j2
kubernetes/helm_charts/datapipeline_jobs/values.j2

Issue #SB-27350 feat: Collection Publish feature

Issue #SB-27350 feat: Collection Publish feature

---

platform-tools/spikes/sync-tool/README.md

Added README.md for sync-tool local setup

Added README.md for sync-tool

---

ansible/inventory/env/group_vars/all.yml
ansible/lp_learning_neo4j_provision.yml

Issue #SB-27030 merge: Release 4.4.0 to 4.5.0

---

pipelines/build/learning/auto_build_deploy

fix: perform pre_checks for to check for allowed tags

fix: perform pre_checks for to check for allowed tags

---

ansible/roles/neo4j-backup/meta/main.yml

fix: install az cli in order to upload backups the azure

fix: install az cli in order to upload backups the azure
